export const JOB_TYPES = {
  LOADER_AGENTES: 'LOADER_AGENTES',
  LOADER_ESTEIRA: 'LOADER_ESTEIRA',
  LOADER_FRAUDE: 'LOADER_FRAUDE',
  LOADER_POSVENDA: 'LOADER_POSVENDA',
  LOADER_AUTORREGULACAO: 'LOADER_AUTORREGULACAO',
  LOADER_CONVENIO_PRAZO: 'LOADER_CONVENIO_PRAZO',
  LOADER_NUVIDEO: 'LOADER_NUVIDEO',
  BACKFILL: 'BACKFILL',
  PROC_MATCH: 'PROC_MATCH',
  PROC_SCORE: 'PROC_SCORE',
  LOADER_TEST_PING: 'LOADER_TEST_PING',
} as const;

export type JobType = (typeof JOB_TYPES)[keyof typeof JOB_TYPES];